<#
.SYNOPSIS
    Checks for Inactive Computers in Active Directory
    
.DESCRIPTION
    Checks for inactive computers in Active Directory by using a csv file 
    generated by Lansweeper or by searching for computers that have a
    LastLogonDate of 30 days by default or set by the parameter entered

.OUTPUTS
    Outputs a file named based on the parameter entered in the directory from 
    which the script was called.
    
.EXAMPLE
    PS>.\getInactiveComputersinAD.ps1
    PS>.\getInactiveComputersinAD.ps1 -FilePath "C:\Path\To\File.csv"
    PS>.\getInactiveComputersinAD.ps1 -DaysInactive 30
    

.NOTES
    Version: 2.0
    Author: Brandon Amundson
    Creation Date: 07/30/2024
    Purpose/Change: Added Script parameters for better operability and
    added documentation

#>

[CmdletBinding(DefaultParameterSetName = 'Dated')]
Param(
    # Path to LanSweeper csv report for comparison
    [Parameter(Mandatory,ParameterSetName = 'File')]
    [string]
    $FilePath = "",
    # Specified Inactive Dates to look for
    [Parameter(Mandatory,ParameterSetName = 'Dated')]
    [int]
    $DaysInactive = 30
)

#Requires -Version 4
#Requires -Modules ActiveDirectory
#Requires -RunAsAdministrator

# Place your script here
$Date = Get-Date -UFormat "%Y-%m-%d"
#Set working file path as the path of this script
Start-Transcript -Path "$PSScriptRoot\..\Logs\InactiveComputersinAD_$Date.log"


Switch ($FilePath)
{
    {$_ -ne ""} {
        $active = get-content $FilePath
        $all = (get-adcomputer -filter *).Name
    
        $inactive = compare $all $active | ? { $_.SideIndicator -eq "<=" } | Select InputObject

        Write-Output $inactive | Out-Default

        $inactive | export-csv -Path "$PSScriptRoot\inactiveComputersinAD_File_$Date.csv" -NoTypeInformation
    }

    {$_ -eq ""} {
    $time = (Get-Date).AddDays(-($DaysInactive))

    $inactive = get-adcomputer -filter { LastLogonTimeStamp -lt $time } -Properties Name,LastLogonDate | select Name,LastLogonDate

    Write-Output $inactive | Out-Default

    $inactive | export-csv -Path "$PSScriptRoot\inactiveComputersinAD_Dated_$Date.csv" -NoTypeInformation
    }
}

Stop-Transcript
